name: Pipeline

on:
  workflow_dispatch:
    #inputs:
    # input_text:
    #    description: "Input text for the pipeline"
    #    type: string
    #    required: true
    #  input_number:
    #    description: "Input number for the pipeline"
    #    type: number
    #    required: true

jobs:
  step1:
    uses: ./.github/workflows/step1.yml
    with:
      input_text: ${{ vars.INPUT_TEXT }}
      input_number: ${{ vars.INPUT_NUMBER }}
  step2:
    needs: step1
    uses: ./.github/workflows/step2.yml
    with:
      input_text: ${{ needs.step1.outputs.output_text }}
      input_number: ${{ fromJson(needs.step1.outputs.output_number) }}
  step3:
    needs: step2
    uses: ./.github/workflows/step3.yml
    with:
      input_text: ${{ needs.step2.outputs.output_text }}
      input_number: ${{ fromJson(needs.step2.outputs.output_number) }}
  step4:
    needs: step3
    uses: ./.github/workflows/step4.yml
    with:
      input_text: ${{ needs.step3.outputs.output_text }}
      input_number: ${{ fromJson(needs.step3.outputs.output_number) }}
