name: W1
on:
  workflow_call:
    inputs:
      input_text:
        default: 'John Snow'
        type: string
        required: true
      input_number:
        type: number
        required: true
        default: 7
  
  workflow_dispatch:
    inputs:
      input_text:
        default: 'John Snow'
        type: string
        required: true
      input_number:
        type: number
        required: true
        default: 7
  
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - id: Primeiro_passo
        shell: bash
        run: |
          INPUT_TEXT="${{inputs.input_text}}"
          INPUT_NUMBER=${{inputs.input_number}}
          FORMATTED_TEXT="${INPUT_TEXT}-${INPUT_NUMBER}"
          MULTIPLIED_TEXT=$((INPUT_NUMBER * 2))
          echo $FORMATTED_TEXT
          echo $MULTIPLIED_TEXT
  
