name: W1

on:
  workflow_call:
    inputs:
      input_text:
        type: string
        required: true
      # input_number:
      #   type: number
      #   required: true
    outputs:
      output_text:
        value: ${{ jobs.first_job.outputs.job_output_text }}
      # output_number:
      #   value: ${{ jobs.first_job.outputs.job_output_number }}

jobs:
  first_job:
    runs-on: ubuntu-24.04
    outputs:
      job_output_text: ${{ steps.first_step.outputs.output_text }}
      job_output_number: ${{ steps.first_step.outputs.output_number }}
    steps:
      - id: first_step
        shell: bash
        run: |
          INPUT_TEXT="${{ inputs.input_text }}"
          # INPUT_NUMBER=${{ inputs.input_number }}
          FORMATTED_TEXT="${INPUT_TEXT}"
          # MULTIPLIED_NUMBER=$((INPUT_NUMBER * 2))

          echo "output_text=$FORMATTED_TEXT" >> "$GITHUB_OUTPUT"
          # echo "output_number=$MULTIPLIED_NUMBER" >> "$GITHUB_OUTPUT"
