name: W1
on:
  workflow_call:
    inputs:
      input_text:
        type: string
        required: true
      input_number:
        type: number
        required: true
  
  workflow_dispatch:
  
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - id: Primeiro_passo
        shell: bash
        run: |
          echo testando
  
